# Generated by Django 5.1 on 2024-09-03 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(blank=True, max_length=200, null=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('p1', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('buttonLabel', models.CharField(blank=True, max_length=200, null=True)),
                ('to', models.CharField(blank=True, max_length=200, null=True)),
                ('cName', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
