# Generated by Django 5.1 on 2024-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsData',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('eventTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('eventDateMonth', models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True)),
                ('eventDateDay', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=2, null=True)),
                ('eventDateTime', models.CharField(blank=True, max_length=50, null=True)),
                ('eventLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('eventDescription', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
