# Generated by Django 5.1 on 2024-09-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_eventsdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eventsData',
            new_name='Event',
        ),
    ]
