# Generated by Django 5.1 on 2024-09-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_rename_eventsdata_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventLocation',
            field=models.CharField(blank=True, default='Bulgariatelep, Arad utca 10, Kolozsvar', max_length=200, null=True),
        ),
    ]
