# Generated by Django 5.1 on 2024-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_event_eventlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='imgUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
