# Generated by Django 5.1 on 2024-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_item_image_alter_event_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='page',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('about', 'Rolunk'), ('alkalmaink', 'Alkalmaink'), ('predikaciok', 'Predikaciok'), ('contact', 'Elérhetőség')], max_length=200, null=True),
        ),
    ]
