# Generated by Django 5.1 on 2024-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_item_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='page',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('about', 'Rolunk'), ('alkalmaink', 'Alkalmaink'), ('predikaciok', 'Predikaciok'), ('contact', 'Elérhetőség'), ('home_sm_card', 'Kiskartyak'), ('home_hero', 'Nagy képek')], max_length=200, null=True),
        ),
    ]
