# Generated by Django 5.1 on 2024-09-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_alter_item_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='page',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('about', 'Rolunk'), ('alkalmaink', 'Alkalmaink'), ('gyerekek', 'Gyerekek'), ('fiatalok', 'Fiatalok'), ('felnottek', 'Felnőttek'), ('zenesIstentiszteletek', 'Zenes Istentiszteletek'), ('csendesNapok', 'Csendes napok'), ('contact', 'Elérhetőség'), ('home_sm_card', 'Kiskartyak - Home'), ('home_hero', 'Nagy képek - Home')], max_length=200, null=True),
        ),
    ]
