# Generated by Django 5.1 on 2024-09-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_alter_item_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainSliderData',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('imgUrl', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subTitle', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='alt',
        ),
    ]
