# Generated by Django 5.1 on 2024-09-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_mainsliderdata_remove_item_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItems',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('cName', models.CharField(blank=True, choices=[('nav-item', 'nav-item'), ('dropdown-link', 'dropdown-link')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('cName', models.CharField(default='nav-item', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='home_app.navitem')),
            ],
        ),
    ]
