# Generated by Django 5.1 on 2024-09-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_navitems_navitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(blank=True, choices=[('about', 'Rolunk'), ('alkalmaink', 'Alkalmaink'), ('gyerekek', 'Gyerekek'), ('fiatalok', 'Fiatalok'), ('felnottek', 'Felnőttek'), ('zenesIstentiszteletek', 'Zenes Istentiszteletek'), ('csendesNapok', 'Csendes napok'), ('contact', 'Elérhetőség')], max_length=200, null=True)),
                ('heroTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('bibleVerse', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
