# Generated by Django 5.1 on 2024-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='page',
            field=models.CharField(blank=True, choices=[('about', 'Rolunk'), ('alkalmaink', 'Alkalmaink'), ('gyerekek', 'Gyerekek'), ('fiatalok', 'Fiatalok'), ('felnottek', 'Felnőttek'), ('zenesIstentiszteletek', 'Zenes Istentiszteletek'), ('csendesNapok', 'Csendes napok'), ('predikaciok', 'Predikaciok'), ('contact', 'Elérhetőség')], max_length=200, null=True),
        ),
    ]
