# Generated by Django 5.1 on 2024-09-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_alter_hero_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preacher',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[('sj', 'Simon János'), ('bi', 'Barta István'), ('other', 'Other')], max_length=200, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
