# Generated by Django 5.1 on 2024-09-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_preacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='preacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='preacher',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
