# Generated by Django 5.1 on 2024-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0016_preacher_image_alter_preacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preacher',
            name='name',
            field=models.CharField(blank=True, choices=[('Simon János', 'Simon János'), ('Barta István', 'Barta István'), ('other', 'Other')], max_length=200, null=True),
        ),
    ]
