# Generated by Django 5.1 on 2024-09-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0018_sermon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='fb_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
