# Generated by Django 5.1 on 2024-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0019_sermon_fb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
