# Generated by Django 5.1 on 2024-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0020_alter_sermon_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('verse1', models.TextField()),
                ('verse2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
