# Generated by Django 5.1 on 2024-09-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0021_dailyverses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
